### PR TITLE
French translation (res/values-fr-rFR/strings.xml)

### PR DESCRIPTION
**Pull request by DontPayAttention**

### CODE REVIEW

**Comment by Fachat31** [comment]
I named the folder "values-fr-FR" but saw that the others have an "r" like "values-it-rIT"

**Comment by DontPayAttention** [comment]
All finished

**Comment by SomeoneHen** [comment]
Dude, I'm translating to Portuguese but I don't know how to add the translation here on github, can you help me?

**Comment by DontPayAttention** [comment]
Don't know where to contact you, I'll put the answer here.
It was my first time too and I don't write code whatsoever.

## Boring explaining part
[Link to understand resources](https://developer.android.com/guide/topics/resources/providing-resources) (just took a quick glance tbh)

- First, the file including all the baseline strings you will translate from is named **_strings.xml_**. It is located in the resources directory ([NClientV2/app/src/main/res/](https://github.com/Dar9586/NClientV2/tree/master/app/src/main/res)), more precisely in the _**values**_ subfolder : [NClientV2/app/src/main/res/values/](https://github.com/Dar9586/NClientV2/tree/master/app/src/main/res/values)

- The resources directory has all the translations in it, all written in different _**values**_ subdirectories on a _**strings.xml**_ file. If you browse the folders I put in the braces, you will find a _**strings.xml**_ file in each which contains the strings translated in the language corresponding to the folder it was in (e.g. for Portuguese, the folder _**values-pt**_ would contain a _**strings.xml**_ file with all the strings translated in Portuguese)
Sans titre

## Doing the job

So, you (probably) have 3 options:

#### 1. You fork the project and translate manually
Obviously, you fork the project. Everything below happens in your fork.
In [this directory](https://github.com/Dar9586/NClientV2/tree/master/app/src/main/res) you create a folder named _**values-pt**_, then you copy [strings.xml](https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values/strings.xml) in, which gives you this: NClientV2/app/src/main/res/values-pt/strings.xml
You edit the _**strings.xml**_, translate everything manually, so you must be careful with special characters ([escaped forms](https://developer.android.com/guide/topics/resources/string-resource#escaping_quotes))
Once finished, you create a pull request.

#### 2. You fork the project and translate with a software (safer)
Same as before but you download [strings.xml](https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values/strings.xml) and translate it with one of these Android apps by importing the file in it: [The Translator](https://f-droid.org/packages/com.sunilpaulmathew.translator/) or [Stringlate](https://f-droid.org/packages/io.github.lonamiwebs.stringlate/) (didn't find a computer alternative)
Then you import the translated **_strings.xml_** in your fork and do a pull request.

#### 3. You just download [strings.xml](https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values/strings.xml) and translate it with a software, then create a detailed issue with the translated file attached to it

**Pull request merged**
